name: Deploying

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: executing remote ssh commands using ssh key
              id: ssh_deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  script: |
                      cd node
                      cd portfolio-web
                      git stash
                      git stash clear
                      git pull
                      npm install
                      npm run build
                      mkdir -p /etc/static-site/portfolio-web
                      rm -rf /etc/static-site/portfolio-web/*
                      mv dist/* /etc/static-site/portfolio-web/
                      chown -R www-data:www-data /etc/static-site/portfolio-web
